module.exports = {
    USER_LOGIN: 'USER_LOGIN',
    ONLINE_USERS_CHANGED: 'ONLINE_USERS_CHANGED',
    LOG_OUT: 'LOG_OUT',
    ROOM_JOINED: 'ROOM_JOINED',
    ROOM_LEFT: 'ROOM_LEFT',
    LOGGED_IN: 'LOGGED_IN',
    ADD_INVITATION: 'ADD_INVITATION',
    DELETE_INVITATION: 'DELETE_INVITATION',
    SET_INVITATIONS: 'SET_INVITATIONS'
};
